services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./storage:/var/www/storage:delegated
      - ./bootstrap/cache:/var/www/bootstrap/cache:delegated
    environment:
      - APP_ENV=production
      - CONTAINER_ROLE=app
    networks:
      - inventory_network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: inventory_mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: your_secure_password
      MYSQL_ROOT_PASSWORD: root_password_123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

volumes:
  mysql_data:

networks:
  inventory_network:
    driver: bridge
