version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env.production
    networks:
      - inventory_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: inventory_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - inventory_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: inventory_mysql
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory_network

volumes:
  mysql_data:

networks:
  inventory_network:
    driver: bridge
